---
apiVersion: v1
kind: Namespace
metadata:
  name:  dbns

---
apiVersion: v1
kind: Service
metadata:
  name: db-hsvc
  namespace: dbns
spec:
  clusterIP: None
  selector:
    app: db
    name: db-sts
  ports:
  - port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dbs-sts
  namespace: dbns
  labels:
    app: db
    name: db-sts
spec:
  selector:
    matchLabels:
      app: db
      name: db-sts
  replicas: 2
  serviceName: db-hsvc
  volumeClaimTemplates:
  - metadata:
      name: data-vol
    spec: 
      storageClassName: do-block-storage
      accessModes: 
      - ReadWriteOnce
      resources: 
        requests:
          storage: 1Gi
  template:
    metadata:
      name: db-po
      namespace: dbns
      labels:
        app: db
        name: db-sts
    spec:
      containers:
      - name: db-container
        image: mysql:8.0.40
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: change_this
        volumeMounts:
        - name:   data-vol
          mountPath: /var/lib/mysql
