---
apiVersion: v1
kind: Pod
metadata: 
  name: dov-pod
  namespace: myns
  labels:
    app: dov
spec:
  containers:
  # spec for a Container resource
  - name: dov-container
    # can also use container image digtest (see docker hub), used in CICD
    image: chukmunnlee/dov-bear:v5
    imagePullPolicy: IfNotPresent #only pull image if not available online
    env:
      - name: INSTANCE_NAME
        value: "bear"
      - name: INSTANCE_HASH
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    ports:
      - containerPort: 3000 # ports exposed by app
