---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-app
  namespace: codeserver
  labels:
    app: cs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: cs
    spec:
      volumes:
      - name: data-vol
        persistentVolumeClaim: 
          claimName: cs-pvc
      containers:
      - name: cs-container
        image: linuxserver/code-server:amd64-latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: cs-cm
          - secretRef:
              name: cs-secret
        volumeMounts:
          - name:  data-vol
            mountPath: /config/workspace
        ports:
        - containerPort: 8443
        resources:
          requests:
            memory: 512M
            cpu: 200m
          limits:
            memory: 512M
            cpu: 200m 

---
apiVersion: v1
kind: Service
metadata:
  name: cs-svc
  namespace: codeserver
spec:
  type: ClusterIP
  selector:
    app: cs
  ports:
  - port: 8443
    targetPort: 8443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cs-ingress
  namespace: codeserver
  labels:
    app: cs
spec:
  ingressClassName: nginx
  rules:
  - host: code-209.38.56.108.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cs-svc
            port: 
              number: 8443 

