---
apiVersion: v1
kind: Namespace
metadata:
  name: codeserver

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cs-cm
  namespace: codeserver
  labels:
    app: cs
data:
  name: code-server
  TZ: Asia/Singapore
  default-workspace: /config/workspace 
  PROXY_DOMAIN: code-209.38.56.108.nip.io

---
apiVersion: v1
kind: Secret
metadata:
  name:  cs-secret
  namespace: codeserver
data:
  PASSWORD: Y2hhbmdlaXQ=
  SUDO_PASSWORD: Y2hhbmdlaXQ=

# on password change, bounce the pods
# get a view of the pods > k get pod -ncodeserver 
# "down" the pods > k delete -ncodeserver <pod name>
# alternatively, delete deployment
# "re-apply" > k apply -f <deployment yaml>