# base image to use
FROM python:3.8

# main dir is this

# attaching a label to my image
LABEL name=workshop01

# Copy over required files
COPY requirements.txt .
COPY templates templates
COPY public public
COPY main.py .
COPY requirements.txt .
COPY main.py .
COPY utils.py .
COPY run.sh .


# install deps
RUN pip install requirements.txt

# expose some ports to external entities
ENV APP_PORT=3000
EXPOSE 3000

# run the app
ENTRYPOINT gunicorn -b ":${PORT:-3000}" --log-level debug main:app 
