# base image to use
FROM python:3.8

# attaching a label to my image
LABEL name=workshop01

# Copy over required files
COPY requirements.txt .
COPY templates templates
COPY public public

# install deps
RUN pip install requirements.txt

# expose some ports to external entities
ENV APP_PORT=3000
EXPOSE 3000

# run the app
ENTRYPOINT gunicorn -b ":${PORT:-3000}" --log-level debug main:app 
