# command used
# kc create deploy bggapp-deploy -nbggns --image stackupiss/bgg-backend:v1 -oyaml --dry-run=client > test-generate-scaffold.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgg-app-deploy
  namespace: bggns
  labels:
    app: bgg-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bgg-app
  template:
    metadata:
      name: bgg-pod
      namespace: bggns
      labels:
        app: bgg-app
    spec:
      containers:
      - image: stackupiss/bgg-backend:v1
        name: bgg-backend
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          periodSeconds: 60
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          periodSeconds: 60
          successThreshold: 1
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secrets
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bgg-app-svc
  namespace: bggns
  labels:
    app: bgg-app
spec:
  type: ClusterIP
  selector:
    app: bgg-app
  ports:
  - name: db-svc-port 
    port: 80
    targetPort: 3000

# forward command due to entry point selection above 
#  kc port-forward svc/bgg-app-svc -nbggns 8080:5000 