---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: bgg-db-deploy
  namespace: bggns
  labels:
    app: bgg-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgg-db
  template:
    metadata:
      name: deploy-db
      namespace: bggns
      labels:
        app: bgg-db
    spec:    
      volumes:
        - name: bgg-vol
          persistentVolumeClaim:
            claimName: bgg-db-pvc
      containers:
      - name: bgg-db-container
        imagePullPolicy: IfNotPresent
        image:  stackupiss/bgg-database:v1
        volumeMounts:
          - name:  bgg-vol
            mountPath: /var/lib/mysql
        ports:
          - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: bgg-db-svc
  namespace: bggns
  labels:
    app: bgg-db
spec:
  # expose this db internally
  type: ClusterIP
  selector:
    app: bgg-db
  ports:
  - name: db-svc-port 
    port: 3306
    targetPort: 3306


# kc run mysql -ti --rm