---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bgg-db-pvc
  namespace: bggns
  labels:
    app: bgg
spec:
  storageClassName: do-block-storage 
  accessModes:
    - ReadWriteOnce
    # - ReadWriteMany -> not supported
  resources:
    requests:
      storage: 1Gi