# good to separate secrets and gitignore them
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
type: Opaque
data:
  # adminadmin
  MINIO_ROOT_PASSWORD: YWRtaW5hZG1pbg==